### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by iamluckey** [amastov/ToMute#1]
Doesn't seem to work anymore?

**Comment by amastov** [comment]
Haha yeah... The DOM for twitch might have changed since I wrote this. I'll take a look at it soon. Pretty sure it wasn't completely working in the first place...

**Comment by iamluckey** [comment]
Cool, thanks for the quick response. One of the streams I watch is really low so I crack up the volume and then the ad comes and kills my ears.

**Comment by amastov** [comment]
Yeah those energy drink ads are really obnoxiously... I figured since they started broadcasting the ads in stream to avoid ad blockers I would try and block the next best thing.

**Comment by iamluckey** [comment]
Any news? :D

**Comment by amastov** [comment]
Yeah, working on it. Sometimes hard to test because I need to wait for a streamer to play an Ad! That's probably what slows me down the most.

**Comment by iamluckey** [comment]
I can help you test if it works on VODs, I usually watch those and they play an ad every 10 mins or so.

**Comment by amastov** [comment]
@iamluckey, this should work now. I've submitted a draft to the chrome store's review, but you can load the extension through chrome://extensions -> "Load unpacked" and select the repo's directory in the meantime.
